#!/bin/bash
# 交互式识别 4 个 CAN 臂的 USB serial，生成 udev 规则，并激活 CAN 接口
# 使用方法: sudo bash bash/identify_arms.sh
#
# 一步到位：识别 → 写入 udev → 重新绑定设备 → 激活 CAN → 验证

set -e

UDEV_RULES_FILE="/etc/udev/rules.d/90-can-yam.rules"
BITRATE=1000000
TXQUEUELEN=1000
ARM_ROLES=("master_l" "master_r" "slave_l" "slave_r")
ARM_LABELS=("主臂左 (Master Left)" "主臂右 (Master Right)" "从臂左 (Slave Left)" "从臂右 (Slave Right)")

declare -A ROLE_SERIAL

# ─────────────────────────────────────────────
# 工具函数
# ─────────────────────────────────────────────

get_can_serials() {
    # 输出所有 CAN 接口的 serial=iface 对
    for iface in $(ls /sys/class/net/ 2>/dev/null | grep -E "^can"); do
        local serial
        serial=$(udevadm info -a "/sys/class/net/$iface" 2>/dev/null \
            | grep 'ATTRS{serial}' | head -1 \
            | sed 's/.*=="\(.*\)"/\1/')
        if [[ -n "$serial" ]]; then
            echo "$serial=$iface"
        fi
    done
}

check_root() {
    if [[ $EUID -ne 0 ]]; then
        echo "请使用 sudo 运行此脚本:"
        echo "  sudo bash bash/identify_arms.sh"
        exit 1
    fi
}

# ─────────────────────────────────────────────
# 主流程
# ─────────────────────────────────────────────

check_root

echo "============================================"
echo "  CAN 臂识别 + 激活工具 (4臂主从遥操作)"
echo "============================================"
echo ""
echo "本脚本将依次完成:"
echo "  1. 扫描所有 CAN 接口"
echo "  2. 通过插拔识别每个臂"
echo "  3. 写入 udev 规则"
echo "  4. 重新绑定设备使名称生效"
echo "  5. 激活所有 CAN 接口"
echo ""
echo "请确保所有 4 个臂的 USB-CAN 适配器都已插上。"
echo ""
read -p "准备好了吗？按 Enter 继续..."

# ──── 步骤 1: 扫描 ────

echo ""
echo "[1/5] 扫描所有 CAN 接口..."
echo ""

ALL_SERIALS=()
ALL_IFACES=()
while IFS='=' read -r serial iface; do
    ALL_SERIALS+=("$serial")
    ALL_IFACES+=("$iface")
    echo "  发现: $iface (serial: $serial)"
done < <(get_can_serials)

echo ""
echo "共发现 ${#ALL_SERIALS[@]} 个 CAN 接口。"

if [[ ${#ALL_SERIALS[@]} -lt 4 ]]; then
    echo ""
    echo "⚠ 警告: 发现少于 4 个接口！请确保都已插上。"
    read -p "是否继续？(y/N) " yn
    [[ "$yn" != "y" && "$yn" != "Y" ]] && exit 1
fi

# ──── 步骤 2: 逐个识别 ────

echo ""
echo "[2/5] 逐个识别每个臂 (拔掉 → 检测 → 插回)"
echo ""

for i in "${!ARM_ROLES[@]}"; do
    role="${ARM_ROLES[$i]}"
    label="${ARM_LABELS[$i]}"

    echo "-------------------------------------------"
    echo "  识别: $label"
    echo "-------------------------------------------"
    echo ""
    echo "  请拔掉 【${label}】 的 USB-CAN 适配器。"
    read -p "  拔掉后按 Enter..."
    sleep 2

    # 获取当前 serial
    CURRENT_SERIALS=()
    while IFS='=' read -r serial iface; do
        CURRENT_SERIALS+=("$serial")
    done < <(get_can_serials)

    # 找出消失的 serial（排除已分配的）
    MISSING=""
    for s in "${ALL_SERIALS[@]}"; do
        found=false
        for c in "${CURRENT_SERIALS[@]}"; do
            [[ "$s" == "$c" ]] && { found=true; break; }
        done
        already_assigned=false
        for assigned in "${ROLE_SERIAL[@]}"; do
            [[ "$s" == "$assigned" ]] && { already_assigned=true; break; }
        done
        if [[ "$found" == false && "$already_assigned" == false ]]; then
            MISSING="$s"
            break
        fi
    done

    if [[ -z "$MISSING" ]]; then
        echo ""
        echo "  ⚠ 未检测到接口消失！"
        echo "  当前在线的 serial:"
        for c in "${CURRENT_SERIALS[@]}"; do echo "    $c"; done
        read -p "  手动输入 serial（或按 Enter 跳过）: " manual_serial
        if [[ -n "$manual_serial" ]]; then
            MISSING="$manual_serial"
        else
            echo "  跳过 $label"
            echo ""
            continue
        fi
    fi

    ROLE_SERIAL["$role"]="$MISSING"
    echo ""
    echo "  → $label = $MISSING"
    echo ""
    echo "  请重新插上该适配器。"
    read -p "  插好后按 Enter..."
    sleep 2
    echo ""
done

# ──── 步骤 3: 显示结果 + 确认 ────

echo ""
echo "============================================"
echo "  识别结果"
echo "============================================"
echo ""

all_identified=true
for i in "${!ARM_ROLES[@]}"; do
    role="${ARM_ROLES[$i]}"
    label="${ARM_LABELS[$i]}"
    serial="${ROLE_SERIAL[$role]:-}"
    if [[ -z "$serial" ]]; then
        echo "  ✗ $label → 未识别"
        all_identified=false
    else
        echo "  ✓ $label → can_${role} (serial: $serial)"
    fi
done

echo ""

if [[ "$all_identified" == false ]]; then
    echo "⚠ 部分臂未识别，建议重新运行脚本。"
    read -p "是否继续写入已识别的部分？(y/N) " yn
    [[ "$yn" != "y" && "$yn" != "Y" ]] && exit 1
fi

# ──── 步骤 4: 写入 udev 规则 ────

echo "[3/5] 写入 udev 规则..."
echo ""

RULES_CONTENT="# CAN device mapping for 4-arm master-slave teleoperation
# Generated by identify_arms.sh on $(date)

# 主臂 (Master arms) - 重力补偿模式，手动引导
SUBSYSTEM==\"net\", ACTION==\"add\", ATTRS{serial}==\"${ROLE_SERIAL[master_l]}\", NAME=\"can_master_l\"
SUBSYSTEM==\"net\", ACTION==\"add\", ATTRS{serial}==\"${ROLE_SERIAL[master_r]}\", NAME=\"can_master_r\"

# 从臂 (Slave arms) - 跟随主臂关节位置
SUBSYSTEM==\"net\", ACTION==\"add\", ATTRS{serial}==\"${ROLE_SERIAL[slave_l]}\", NAME=\"can_slave_l\"
SUBSYSTEM==\"net\", ACTION==\"add\", ATTRS{serial}==\"${ROLE_SERIAL[slave_r]}\", NAME=\"can_slave_r\"
"

echo "$RULES_CONTENT"

# 备份旧文件
if [[ -f "$UDEV_RULES_FILE" ]]; then
    cp "$UDEV_RULES_FILE" "${UDEV_RULES_FILE}.bak.$(date +%s)"
    echo "  已备份旧规则文件"
fi

echo "$RULES_CONTENT" > "$UDEV_RULES_FILE"
echo "  已写入 $UDEV_RULES_FILE"

# ──── 步骤 5: 重新绑定设备使名称生效 ────

echo ""
echo "[4/5] 重新绑定 USB 设备，使 CAN 接口名称生效..."
echo ""

udevadm control --reload-rules

# 对每个现有 CAN 接口执行 udevadm trigger 重新命名
for iface in $(ls /sys/class/net/ 2>/dev/null | grep -E "^can"); do
    syspath=$(udevadm info -q path "/sys/class/net/$iface" 2>/dev/null)
    if [[ -n "$syspath" ]]; then
        udevadm trigger --action=add "/sys/$syspath" 2>/dev/null || true
    fi
done

sleep 3

echo "  当前 CAN 接口:"
for iface in $(ls /sys/class/net/ 2>/dev/null | grep -E "^can"); do
    echo "    $iface"
done

# 检查名称是否正确
EXPECTED_IFACES=("can_master_l" "can_master_r" "can_slave_l" "can_slave_r")
missing_ifaces=()
for exp in "${EXPECTED_IFACES[@]}"; do
    if [[ ! -d "/sys/class/net/$exp" ]]; then
        missing_ifaces+=("$exp")
    fi
done

if [[ ${#missing_ifaces[@]} -gt 0 ]]; then
    echo ""
    echo "  ⚠ 以下接口未出现（可能需要重新插拔适配器）:"
    for m in "${missing_ifaces[@]}"; do echo "    $m"; done
    echo ""
    echo "  请拔掉所有 4 个适配器，等 3 秒，然后全部插回。"
    read -p "  插好后按 Enter..."
    sleep 3

    echo "  重新检查..."
    missing_ifaces=()
    for exp in "${EXPECTED_IFACES[@]}"; do
        if [[ ! -d "/sys/class/net/$exp" ]]; then
            missing_ifaces+=("$exp")
        fi
    done

    if [[ ${#missing_ifaces[@]} -gt 0 ]]; then
        echo "  ⚠ 仍有接口缺失: ${missing_ifaces[*]}"
        echo "  将尝试激活已有的接口。"
    else
        echo "  ✓ 所有接口已就绪"
    fi
else
    echo "  ✓ 所有接口名称正确"
fi

# ──── 步骤 6: 激活 CAN ────

echo ""
echo "[5/5] 激活 CAN 接口 (bitrate=${BITRATE}, txqueuelen=${TXQUEUELEN})..."
echo ""

for iface in "${EXPECTED_IFACES[@]}"; do
    if [[ -d "/sys/class/net/$iface" ]]; then
        ip link set "$iface" down 2>/dev/null || true
        ip link set "$iface" up type can bitrate $BITRATE
        ip link set "$iface" txqueuelen $TXQUEUELEN
        state=$(cat "/sys/class/net/$iface/operstate" 2>/dev/null || echo "unknown")
        echo "  ✓ $iface  已激活 (state: $state)"
    else
        echo "  ✗ $iface  不存在，跳过"
    fi
done

# ──── 完成 ────

echo ""
echo "============================================"
echo "  全部完成！"
echo "============================================"
echo ""
echo "  CAN 接口状态:"
ip -d link show | grep -A1 -E "can_(master|slave)" | grep -E "(can_|bitrate|state)" || true
echo ""
echo "  可以运行主从遥操作了:"
echo "    bash bash/run_master_slave.sh"
echo ""
